---
services:
  posterizarr:
    hostname: "posterizarr"
    container_name: "posterizarr"
    environment:
      - "TZ=Europe/Paris"
      - "TERM=xterm"
      - "RUN_TIME=disabled"
    image: "ghcr.io/fscorrupt/posterizarr:latest"
    restart: "unless-stopped"
    user: "1000:1000"
    ports:
      - "xxxx:8000"
    networks:
      - "proxy"
    volumes:
      - "/opt/appdata/posterizarr:/config:rw"
      - "/opt/appdata/posterizarr/assets:/assets:rw"
      - "/opt/appdata/posterizarr/assetsbackup:/assetsbackup:rw"
      - "/opt/appdata/posterizarr/manualassets:/manualassets:rw"
networks:
  proxy:
    driver: bridge
    external: true