version: "3.8"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    environment:
      - TZ=Europe/Paris
      # Monitoring of existing Docker containers
      - DIUN_PROVIDERS_DOCKER=true
      # Verification interval (here, every 6 hours)
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      # Discord Notification via Webhook
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    labels:
      - "diun.enable=true"