version: "3.8"
services:
  db:
    image: mariadb:11
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxx
      MYSQL_DATABASE: xxxxxxxx
      MYSQL_USER: xxxxxxxx
      MYSQL_PASSWORD: xxxxxxxx
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - xxxx:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /data/nextcloud_data:/var/www/html/data
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: xxxxxxxx
      MYSQL_USER: xxxxxxxx
      MYSQL_PASSWORD: xxxxxxxx

volumes:
  db_data:
  nextcloud: